//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DHTDTTDNEntities1 : DbContext
    {
        public DHTDTTDNEntities1()
            : base("name=nckh_dhdnEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DetailStatementLe> DetailStatementLes { get; set; }
        public virtual DbSet<DetailStatementSt> DetailStatementSts { get; set; }
        public virtual DbSet<Extension> Extensions { get; set; }
        public virtual DbSet<ImgObj> ImgObjs { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PointTable> PointTables { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_file> tbl_file { get; set; }
        public virtual DbSet<TopicOfLecture> TopicOfLectures { get; set; }
        public virtual DbSet<TopicOfStudent> TopicOfStudents { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    
        public virtual ObjectResult<sp_get_file_details_Result> sp_get_file_details(Nullable<int> file_id)
        {
            var file_idParameter = file_id.HasValue ?
                new ObjectParameter("file_id", file_id) :
                new ObjectParameter("file_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_file_details_Result>("sp_get_file_details", file_idParameter);
        }
    }
}
